base.install: Make it work on 64bit hosts
Commit 9956b4d6a7131d4fecdbd49dd63d9c32993f9260 broke the arch
detection. "-e" shall be enabled once the uname | grep failed is done
unless no one can use it.

diff --git a/build/base.install b/build/base.install
--- a/build/base.install
+++ b/build/base.install
@@ -207,13 +207,14 @@ cleanup() {
     fi
 }
 
+############################
+########## MAIN ############
+############################
+
 if [ -z "$1" -o -z "$dist" -o -z "$version" ]; then
    echo "Usage: $0 <directory name> <distro name>" 1>&2
    exit 1
 fi
-
-set -e              # abort on failure
-set -x              # print commands
 
 check_binary dh_testdir
 check_binary alien
@@ -228,6 +229,9 @@ if [ $? -eq 0 ]; then
     echo "Exiting"
     exit 1
 fi
+
+set -e              # abort on failure
+set -x              # print commands
 
 case $dist in
     centos*)
