build: factorize code between upgrade and .install files

diff --git a/build/common b/build/common
--- a/build/common
+++ b/build/common
@@ -1,3 +1,5 @@
+# -*- shell-script -*-
+
 compress() {
     COMPRESS=gzip
     if [ ! -z $(which pigz 2>/dev/null) ]; then
@@ -32,63 +34,65 @@ EOF
 }
 
 install_mellanox() {
-RELEASE=$1
-CHROOT=$2
-URL=http://www.mellanox.com/downloads/ofed/MLNX_OFED-2.0-3.0.0/
-FILE=
-KVER=
-KVER_TO_REMOVE=
-PACKAGES=
-case $RELEASE in
-    precise)
-    KVER=3.5.0-42-generic
-    KVER_TO_REMOVE=3.8.0-32
-    FILE="MLNX_OFED_LINUX-2.0-3.0.0-ubuntu12.04-x86_64.tgz"
-    URL="$URL/$FILE"
-    # Thoses packages will be installed by mellanox but one by one ....
-    # Let's install them at once to save time
-    PACKAGES="autotools-dev autoconf libtool automake1.10 automake debhelper tcl tcl8.4 chrpath swig graphviz tcl-dev tcl8.4-dev tk-dev tk8.4-dev bison flex dpatch libcurl4-gnutls-dev python-libxml2 libvirt-bin"
-    PACKAGES="$PACKAGES linux-image-$KVER linux-headers-$KVER"
-    # We shall only keep the final kernel unless kernel-mft-dkms fails at compiling
-    PACKAGES_TO_REMOVE="linux-image-$KVER_TO_REMOVE-generic linux-headers-$KVER_TO_REMOVE-generic linux-headers-$KVER_TO_REMOVE"
-    ;;
-    *)
-    ;;
-esac
+    RELEASE=$1
+    CHROOT=$2
+    URL=http://www.mellanox.com/downloads/ofed/MLNX_OFED-2.0-3.0.0/
+    FILE=
+    KVER=
+    KVER_TO_REMOVE=
+    PACKAGES=
+    case $RELEASE in
+	precise)
+	    KVER=3.5.0-42-generic
+	    KVER_TO_REMOVE=3.8.0-32
+	    FILE="MLNX_OFED_LINUX-2.0-3.0.0-ubuntu12.04-x86_64.tgz"
+	    URL="$URL/$FILE"
+	    # Thoses packages will be installed by mellanox but one by one ....
+	    # Let's install them at once to save time
+	    PACKAGES="autotools-dev autoconf libtool automake1.10 automake debhelper tcl tcl8.4 chrpath swig graphviz tcl-dev tcl8.4-dev tk-dev tk8.4-dev bison flex dpatch libcurl4-gnutls-dev python-libxml2 libvirt-bin"
+	    PACKAGES="$PACKAGES linux-image-$KVER linux-headers-$KVER"
+	    # We shall only keep the final kernel unless kernel-mft-dkms fails at compiling
+	    PACKAGES_TO_REMOVE="linux-image-$KVER_TO_REMOVE-generic linux-headers-$KVER_TO_REMOVE-generic linux-headers-$KVER_TO_REMOVE"
+	    ;;
+	*)
+	    ;;
+    esac
 
-# As we are chroot, we have to prevent some services to be restarted by packages
-# This prevent failures
-prevent_services_to_run $CHROOT on
+    # As we are chroot, we have to prevent some services to be restarted by packages
+    # This prevent failures
+    prevent_services_to_run $CHROOT on
 
-for mydir in /proc /dev /sys /dev/pts /run; do
-    mount $mydir $CHROOT/$mydir -o bind || echo "Failed at binding $mydir"
-done
-chroot $CHROOT apt-get  -y --force-yes purge $PACKAGES_TO_REMOVE
-chroot $CHROOT apt-get -y --force-yes install $PACKAGES
+    for mydir in /proc /dev /sys /dev/pts /run; do
+	mount $mydir $CHROOT/$mydir -o bind || echo "Failed at binding $mydir"
+    done
+    chroot $CHROOT apt-get  -y --force-yes purge $PACKAGES_TO_REMOVE
+    chroot $CHROOT apt-get -y --force-yes install $PACKAGES
 
-wget -q -N $URL
-cp $FILE $CHROOT
-cd $CHROOT
-tar -xf $FILE
-cd -
+    wget -q -N $URL
+    cp $FILE $CHROOT
+    cd $CHROOT
+    tar -xf $FILE
+    cd -
 
-# We need to perform many task in the chroot, let's make a script for that
-cat > $CHROOT/doit.sh << EOF
+    # We need to perform many task in the chroot, let's make a script for that
+    cat > $CHROOT/doit.sh << EOF
+#!/bin/bash
+
 # To avoid dkms from failing, let's insure we have the headers well installed
 cd /lib/modules/
-    ln -sf $KVER `uname -r`
-    rm -rf $KVER_TO_REMOVE*
+ln -sf $KVER `uname -r`
+rm -rf $KVER_TO_REMOVE*
 
-    #Mellanox is installing dkms drivers but they do conflict
-    #with the existing ones. So let's get them out of the tree.
-    mkdir -p $KVER-obsolete/kernel/drivers/net/ethernet/mellanox
-    mv $KVER/kernel/drivers/infiniband $KVER-obsolete/kernel/drivers
-    mv $KVER/kernel/drivers/net/ethernet/mellanox/ $KVER-obsolete/kernel/drivers/net/ethernet/mellanox/
+#Mellanox is installing dkms drivers but they do conflict
+#with the existing ones. So let's get them out of the tree.
+mkdir -p $KVER-obsolete/kernel/drivers/net/ethernet/mellanox
+mv $KVER/kernel/drivers/infiniband $KVER-obsolete/kernel/drivers
+mv $KVER/kernel/drivers/net/ethernet/mellanox/ $KVER-obsolete/kernel/drivers/net/ethernet/mellanox/
 cd -
 
 cd /lib/modules/$KVER
-    ln -sf build source
-    ln -sf x86 build/arch/amd64
+ln -sf build source
+ln -sf x86 build/arch/amd64
 cd -
 
 DIRNAME=$(echo $FILE | sed -e 's/\.tgz//g')
@@ -113,20 +117,20 @@ rm -f /lib/modules/`uname -r`
 depmod -a $KVER
 EOF
 
-chmod +x $CHROOT/doit.sh
-chroot "$CHROOT" /doit.sh
-# Let's revert our change, we now can run services
-prevent_services_to_run $CHROOT off
+    chmod +x $CHROOT/doit.sh
+    chroot "$CHROOT" /doit.sh
+    # Let's revert our change, we now can run services
+    prevent_services_to_run $CHROOT off
 
-#Let's tweak the grub setup to boot the proper kernel with intel_iommu for SR_IOV
-#Grub will be updates/installed when eDeploy will install it on the real server
-sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT="intel_iommu=on"/g' $CHROOT/etc/default/grub
+    #Let's tweak the grub setup to boot the proper kernel with intel_iommu for SR_IOV
+    #Grub will be updates/installed when eDeploy will install it on the real server
+    sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT="intel_iommu=on"/g' $CHROOT/etc/default/grub
 
-for mydir in /proc /dev/pts /sys /dev/ /run; do
-    umount $CHROOT/$mydir
-done
+    for mydir in /proc /dev/pts /sys /dev/ /run; do
+	umount $CHROOT/$mydir
+    done
 
-rm -f $CHROOT/doit.sh
+    rm -f $CHROOT/doit.sh
 }
 
 
@@ -173,4 +177,65 @@ do_chroot() {
     shift
     REMAIN=$@
     PATH=/bin/:/sbin:$PATH chroot $DIR bash -c "export LANG=C; export LC_ALL=C; export LC_CTYPE=C; export LANGUAGE=C; $REMAIN"
+}
+
+# Called to clean packages, temporary files and to create the compressed archive
+# usually by a "trap cleanup 0" in a script
+cleanup() {
+    ret=$?
+    if [ ! -d "${dir}" ]; then
+	return
+    fi
+    rm -f "${dir}"/etc/default/grub.d/edeploy.cfg
+    chroot ${dir} bash -c "apt-get clean || rm -rf /var/cache/yum"
+    for mpoint in /dev /proc; do
+	a=10
+	while ! umount ${dir}$mpoint; do
+	    sleep 1
+	    a=$(($a - 1))
+	    if [ $a -eq 0 ]; then
+		break
+	    fi
+	done
+    done
+    if [ $ret = 0 ]; then
+	if [ -x ${dir}/usr/bin/dpkg ]; then
+	    chroot ${dir} dpkg -l > ${dir}/../${ROLE}.packages
+	else
+	    chroot ${dir} rpm -qa > ${dir}/../${ROLE}.packages
+	fi
+
+	cd ${dir}
+
+	rm -f ../../${ROLE}-${version}.edeploy
+
+	tar c . | compress -9v > ../../${ROLE}-${version}.edeploy
+    fi
+}
+
+common_setup() {
+    # export these variables to let them be used by upgrade-from sub-scripts
+    export OS=$(chroot ${dir} lsb_release -i -s)
+    export RELEASE=$(chroot ${dir} lsb_release -c -s)
+    export CODENAME=$(chroot ${dir} lsb_release -r -s)
+    
+    # Resolv.conf got setup during the initial deboostrap
+    # But since, you might have change your host to another network (office vs home vs mobile vs ...)
+    # In such case, the resolv.conf is wrong and prevents apt (and all networking-depedent stuff from working)
+    # So let's copy the current one to insure the setup is good
+    cp -f /etc/resolv.conf "$dir/etc/"
+
+    set -x
+
+    echo -e "\nRole ${ROLE}\nVersion ${version}\n" > ${dir}/etc/motd
+    echo -e "VERS=${version}\nROLE=${ROLE}\n" > ${dir}/var/lib/edeploy/conf
+
+    export DEBIAN_FRONTEND=noninteractive
+
+    # magical stuff to let kernel upgrade work
+    mkdir -p "${dir}"/etc/default/grub.d
+    echo 'exit 0' > "${dir}"/etc/default/grub.d/edeploy.cfg
+    mount -obind /dev ${dir}/dev
+    mount -t proc none ${dir}/proc
+    trap cleanup 0
 }
diff --git a/build/upgrade-from b/build/upgrade-from
--- a/build/upgrade-from
+++ b/build/upgrade-from
@@ -22,16 +22,22 @@ FROM="$2"
 TO="$3"
 DEST="$4"
 
-ORIG=$(cd $(dirname $0); pwd)
+BUILDDIR=$(cd $(dirname $0); pwd)
 FDIR=${DEST}/install/${FROM}/${ROLE}
 TDIR=${DEST}/install/${TO}/${ROLE}
-METADATA_DIR=${DEST}/metadata/${FROM}/${ROLE}/${TO}
+METADATA_DIR=${BUILDDIR}/../metadata/${FROM}/${ROLE}/${TO}
 EXCLUDE_FILE=${METADATA_DIR}/exclude
 ADD_ONLY_FILE=${METADATA_DIR}/add_only
 
+. $BUILDDIR/common
+
+# for compatibility with cleanup and common_setup from common
+dir=${TDIR}
+version=${TO}
+
 setup_add_only() {
     if [ ! -f $ADD_ONLY_FILE ]; then
-        PRIOR_ADD=$(find ${DEST}/metadata/*/${ROLE}/${FROM}/add_only || true)
+        PRIOR_ADD=$(find ${BUILDDIR}/../metadata/*/${ROLE}/${FROM}/add_only || true)
         if [ ! -z $PRIOR_ADD ]; then
             echo "Found an add_only file for release ${FROM}"
             echo "Let's use it as default for this version too"
@@ -53,7 +59,7 @@ EOF
 }
 setup_exclude() {
     if [ ! -f $EXCLUDE_FILE ]; then
-        PRIOR_EXCLUDE=$(find ${DEST}/metadata/*/${ROLE}/${FROM}/exclude || true)
+        PRIOR_EXCLUDE=$(find ${BUILDDIR}/../metadata/*/${ROLE}/${FROM}/exclude || true)
         if [ ! -z $PRIOR_EXCLUDE ]; then
             echo "Found an exclude file for release ${FROM}"
             echo "Let's use it as default for this version too"
@@ -117,10 +123,7 @@ if [ ! -d "$FDIR" ]; then
     exit 1
 fi
 
-export DEBIAN_FRONTEND=noninteractive
-
 set -e
-set -x
 
 if [ ! -d ${TDIR} ]; then
     mkdir -p ${TDIR}
@@ -130,19 +133,15 @@ echo -n "Syncing ${FDIR} to ${TDIR}..."
 rsync -a --delete-before ${FDIR}/ ${TDIR}/
 echo "done"
 
-cleanup() {
-    umount ${TDIR}/dev
-}
+common_setup
 
-trap cleanup 0
+if [ -x ${TDIR}/usr/bin/dpkg ]; then
+    chroot ${TDIR} apt-get update
+else
+    chroot ${TDIR} yum update
+fi
 
-mount -obind /dev ${TDIR}/dev
-chroot ${TDIR} apt-get update
-cp -p ${ORIG}/edeploy ${TDIR}/usr/sbin/
-echo -e "VERS=${TO}\nROLE=${ROLE}\n" > ${TDIR}/var/lib/edeploy/conf
-
-mkdir -p ${TDIR}/etc/default/grub.d
-echo 'exit 0' > ${TDIR}/etc/default/grub.d/edeploy.cfg
+cp -p ${BUILDDIR}/edeploy ${TDIR}/usr/sbin/
 
 script="$BASE".d/${ROLE}_${FROM}_${TO}.upgrade
 
@@ -150,9 +149,7 @@ if [ -x "$script" ]; then
     "$script" $ROLE $FROM $TO $TDIR
 fi
 
-rm -f ${TDIR}/etc/default/grub.d/edeploy.cfg
-
-chroot ${TDIR} apt-get clean
-chroot ${TDIR} dpkg -l > ${TDIR}/../${ROLE}.dpkg
-
 setup_metadata
+
+mkdir -p ${TDIR}/var/lib/edeploy/${TO}
+cp ${METADATA_DIR}/exclude ${TDIR}/var/lib/edeploy/${TO}/exclude
