build: Adding check_variables()
When building edeploy, it's mandatory to get absolute an absolute path
for TOP unless it will fail at deleting or umounting stuff.

This commit add a sanity check to avoid this mistake seen in the CI.

diff --git a/build/common b/build/common
--- a/build/common
+++ b/build/common
@@ -8,6 +8,10 @@ fatal_error() {
     exit 1
 }
 
+check_variables() {
+	echo $TOP | grep -q '^/' || fatal_error "TOP_DIR ($TOP) shall be absolute, not relative"
+}
+
 compress() {
     COMPRESS=gzip
     if [ ! -z $(which pigz 2>/dev/null) ]; then
