build/edeploy: during upgrade on a failing post abort the command

diff --git a/build/edeploy b/build/edeploy
--- a/build/edeploy
+++ b/build/edeploy
@@ -85,19 +85,30 @@ function upgrade() {
     rsync -av --numeric-ids --delete-after --exclude-from=exclude rsync://${RSERV}:${RSERV_PORT}/${RPATH}/${TARGET}/${ROLE}/ / > ${EDEPLOY_DIR}/rsync_${VERS}_${TARGET}.out
     rsync -av --numeric-ids --ignore-existing --include-from=add_only rsync://${RSERV}:${RSERV_PORT}/${RPATH}/${TARGET}/${ROLE}/ / >> ${EDEPLOY_DIR}/rsync_${VERS}_${TARGET}.out
 
-    set +e
-
     if [ -x post ]; then
+        # suspend abort on error to get the exit code
+        set +e
+
         ./post
         RET=$?
+
+        set -e
+        
+        # 0 or 100 are the only normal exit codes
+        if [ $RET -ne 100 -a $RET -ne 0 ]; then
+            exit $RET
+        fi
+    else
+        RET=0
     fi
+
 
     echo -e "\nVersion ${TARGET}\n" > /etc/motd
     echo -e "VERS=${TARGET}\nROLE=${ROLE}\nRSERV=${RSERV}\nRSERV_PORT=${RSERV_PORT}\nRPATH=${RPATH}\n" > ${EDEPLOY_DIR}/conf
 
     echo "Upgraded to $TARGET"
 
-    if [ "$RET" = "100" ]; then
+    if [ $RET -eq 100 ]; then
         echo "Reboot requested by the upgrade process..."
         sync
         sleep 2
