init: Reporting if PXEMGNR was succesfull or not
We had a case were the PXEMGNR didn't work on the server side by
returning a 404. We had no proof during the deploiement that it fails as
no message was printed in the log file.

This patch does make an explicit report if it succeed or failed to allow
such analysis.

diff --git a/build/init b/build/init
--- a/build/init
+++ b/build/init
@@ -395,6 +395,12 @@ if /configure; then
             # Ask pxemngr to boot locally on the next PXE boot
             if [ -n "$PXEMNGR_URL" ]; then
                 curl -s ${PXEMNGR_URL}localboot/
+                EXIT_CODE="$?"
+                if [ "$EXIT_CODE" != "0" ]; then
+                    log "PXEMNGR: Curl failed ($EXIT_CODE) asking a localboot at ${PXEMNGR_URL}"
+                else
+                    log "PXEMNGR: Server will reboot locally"
+                fi
             fi
 
             umount $d/run
