init: factorize grub1 and grub2 code. Allow cloud-init to work in kexec mode

diff --git a/build/init b/build/init
--- a/build/init
+++ b/build/init
@@ -162,7 +162,7 @@ if /configure; then
 
     if [ -n "$ROLE" -a -n "$VERS" ]; then
 	if [ ! -z "$HSERV" ]; then
-	    log_n "Transfering files from http://${HSERV}/install/${ROLE}-${VERS}.edeploy..."
+	    log_n "Transfering files from http://${HSERV}:${HSERV_PORT}/install/${ROLE}-${VERS}.edeploy..."
 	    curl -s -S http://${HSERV}:${HSERV_PORT}/install/${ROLE}-${VERS}.edeploy | gzip -d | tar x -C $d
 	else
 	    log_n "Copying files from rsync://${RSERV}:${RSERV_PORT}/install/${VERS}/${ROLE}..."
@@ -182,6 +182,7 @@ if /configure; then
 
 	if [ -n "${METADATA_URL}" ]; then
 	    sed -i -e "s@GRUB_CMDLINE_LINUX_DEFAULT=.*@GRUB_CMDLINE_LINUX_DEFAULT=\"ds=nocloud-net\\\\;s=${METADATA_URL}\"@" $d/etc/default/grub
+	    BOOT_ARG=" ds=nocloud-net;s=${METADATA_URL}"
 	fi
 
 	mount -obind /dev $d/dev
@@ -203,56 +204,54 @@ if /configure; then
 	echo  "################################################################################################"
 	echo  "# Installing grub  on device ${DISK} which is a $MODEL from $VENDOR with SN=$SER"
 	echo  "################################################################################################"
-	sleep 3
-	if [ -e "${d}/etc/redhat-release" ]; then
-		chroot $d /bin/bash -c "cat /proc/mounts > /etc/mtab"
-		chroot $d /bin/bash -c "/sbin/grub-install ${DISK}"
-		ROOT_DEVICE=`mount | grep /chroot | awk '{print $1}'`
-		eval `blkid $ROOT_DEVICE -o export`
-		echo "default=0"  > ${d}/boot/grub/grub.conf
-		echo "timeout=5" >> ${d}/boot/grub/grub.conf
-		echo "hiddenmenu">> ${d}/boot/grub/grub.conf
-		for kernel in ${d}/boot/vmlinuz-*; do
-			kversion=`echo $kernel | awk -F'vmlinuz-' '{print $NF}'`;
-			KERNEL="/boot/vmlinuz-${kversion}"
-			INITRD="/boot/initramfs-${kversion}.img"
-			TITLE="CentOS (${kversion})"
-			echo "title $TITLE" >> ${d}/boot/grub/grub.conf
-			echo "	root (hd0,0)" >> ${d}/boot/grub/grub.conf
-			echo "	kernel $KERNEL root=UUID=$UUID nomodeset quiet" >> ${d}/boot/grub/grub.conf
-			echo "	initrd $INITRD" >> ${d}/boot/grub/grub.conf
-		done
-		umount $d/sys
-		umount $d/dev
-		umount $d/proc
-		save_log
-		sync
-		if [ "$DEBUG" != 1 ]; then
-			umount -a
-			reboot -f
-		fi
+	# grub1 doesn't have /usr/sbin/grub-mkconfig
+	if [ ! -x $d/usr/sbin/grub-mkconfig ]; then
+	    chroot $d /bin/bash -c "cat /proc/mounts > /etc/mtab"
+	    chroot $d /bin/bash -c "/sbin/grub-install ${DISK}"
+	    ret=$?
+	    root=`mount | grep /chroot | awk '{print $1}'`
+	    eval `blkid $root -o export`
+	    echo "default=0"  > ${d}/boot/grub/grub.conf
+	    echo "timeout=5" >> ${d}/boot/grub/grub.conf
+	    echo "hiddenmenu">> ${d}/boot/grub/grub.conf
+	    for kernel in ${d}/boot/vmlinuz-*; do
+		kversion=`echo $kernel | awk -F'vmlinuz-' '{print $NF}'`;
+		KERNEL="/boot/vmlinuz-${kversion}"
+		INITRD="/boot/initramfs-${kversion}.img"
+		TITLE="CentOS (${kversion})"
+		echo "title $TITLE" >> ${d}/boot/grub/grub.conf
+		echo "	root (hd0,0)" >> ${d}/boot/grub/grub.conf
+		echo "	kernel $KERNEL root=UUID=$UUID nomodeset quiet" >> ${d}/boot/grub/grub.conf
+		echo "	initrd $INITRD" >> ${d}/boot/grub/grub.conf
+	    done
 	elif chroot $d /bin/bash -c "/usr/sbin/grub-install ${DISK}"; then
-			chroot $d /bin/bash -c "/usr/sbin/grub-mkconfig -o /boot/grub/grub.cfg"
-		umount $d/sys
-		umount $d/dev
-		umount $d/proc
-		save_log
-		sync
-		if [ "$DEBUG" != 1 ]; then
+	    chroot $d /bin/bash -c "/usr/sbin/grub-mkconfig -o /boot/grub/grub.cfg"
+	    ret=$?
+	else
+	    ret=1
+	fi
+	
+	if [ $ret -eq 0 ]; then
+	    umount $d/sys
+	    umount $d/dev
+	    umount $d/proc
+	    save_log
+	    sync
+	    if [ "$DEBUG" != 1 ]; then
 		if [ "$NOREBOOT" = 1 ]; then
 		    if type -p kexec; then
-			echo "Trying kexec..."
-			cp $d/boot/vmlinuz* /tmp/vmlinuz
-			cp $d/boot/initrd.img* /tmp/initrd.img
-			eval $(grep root=UUID= $d/boot/grub/grub.cfg|head -1|tr ' ' '\n'|grep '^root=UUID=')
-			umount $d
-			if [ -z "$root" ]; then
-			    echo "unable to detect root device"
-			else
-			    kexec -l /tmp/vmlinuz --initrd=/tmp/initrd.img --append="root=$root"
-			    kexec -e
-			fi
-		    fi
+    		    	echo "Trying kexec..."
+    		    	cp $d/boot/vmlinuz* /tmp/vmlinuz
+    		    	cp $d/boot/initrd.img* /tmp/initrd.img
+    		    	eval $(grep root=UUID= $d/boot/grub/grub.cfg|head -1|tr ' ' '\n'|grep '^root=UUID=')
+    		    	umount $d
+    		    	if [ -z "$root" ]; then
+    		    	    echo "unable to detect root device"
+    		    	else
+    		    	    kexec -l /tmp/vmlinuz --initrd=/tmp/initrd.img --append="root=${root}${BOOT_ARG}"
+    		    	    kexec -e
+    		    	fi
+    		    fi
 		fi
 		umount -a
 		reboot -f
