catch the case update-rc.d failed
update-rc.d may fail if the init script has invalid LSB headers.
https://bugs.launchpad.net/galera/+bug/1263027

diff --git a/build/packages b/build/packages
--- a/build/packages
+++ b/build/packages
@@ -68,7 +68,10 @@ disable_service() {
     case "$OS" in
         "Debian"|"Ubuntu")
         if ! egrep '# Default-Start:\s*$' ${chroot}/etc/init.d/$service; then
-            do_chroot ${chroot} update-rc.d $service disable
+            if ! do_chroot ${chroot} update-rc.d $service disable; then
+                echo "update-rc.d failed, dropping the init.d symlink manually"
+                find /etc/rc2.d/ -regex '/etc/rc2.d/S[0-9][0-9]'$service'$' -delete
+            fi
         fi
          ;;
         "CentOS"|"RedHatEnterpriseServer")
