base: Removing system from satellite after building
When building an RHEL system, we have to use satellite.

But we don't want to
- saturate the number of deploied system
- let the system configured with an enovance account

So for each built target, we need to setup the satellite and remove it
at the end of the build. This way, we don't consume too much deployed
system on the satellite and we don't let configured systems.

On the other hand, we are not keeping a trace of the system inside the
satellite web interface making more difficult to track if updates are
available for a given role.

This is based on a python script found on a mailing list and adapted to
our needs (remove_system_on_satellite). It adds a perl-Frontier
dependency but it saves time regarding porting it in python.

Note also that calls to unregister_satellite() &
add_satellite_repository() are called from cleanup() and common_setup().
This implies that signal trap shall be enabled as soon a possible to
avoid some virtual FS (/dev/ etc..) mounted if this calls fails.

Last point about this commit, a small rework regarding the cleanup()
code to avoid the case statement. That made lots of code duplication and
very tough to read. Instead of that, we use a variable named
(STRIPPED_TARGET) to tell cleanup() not to try remove packages in it.

diff --git a/build/packages b/build/packages
--- a/build/packages
+++ b/build/packages
@@ -34,6 +34,39 @@ add_epel_repository() {
   esac
 }
 
+unregister_satellite() {
+    local dist=$1
+    local target=$2
+    local builddir=$(dirname $0)
+    local cmd=$builddir/remove_system_on_satellite
+
+    # Let's to the basic tests here
+    # This have only a meaning for redhat systems
+    case "$dist" in
+        redhat)
+
+        # Let's remove the systemid from the chroot
+        if [ -f $target/etc/sysconfig/rhn/systemid ]; then
+            rm -f $target/etc/sysconfig/rhn/systemid || fatal_error "Cannot delete systemid in unregister_satellite()"
+        fi
+
+        if [ ! -x $cmd ]; then
+            fatal_error "$cmd is mandatory to remove the satellite repository"
+        fi
+        # Let's be sure that delete-old-systems-interactive can be run on the system
+        $cmd 2>&1 | grep -qi failed && fatal_error "$cmd is missing dependencies"
+        ;;
+        *)
+        return
+        ;;
+    esac
+
+    $cmd --system=edeploy --user=$SATELLITE_USERNAME --password=$SATELLITE_PASSWORD
+    if [ "$?" != "0" ]; then
+        echo "Failed at removing system from satellite"
+    fi
+}
+
 add_satellite_repository() {
   local dist=$1
   local target=$2
