build/repositories: add add_rh_cdn_repo
add_rh_cdn_repo is a new function in build/repositories used to add a
repository from CDN Red Hat channels.
This is the recommanded way to install Red Hat Enterprise Linux
OpenStack Platform 5.

Source: http://goo.gl/BCwNbU
Signed-off-by: Emilien Macchi <emilien.macchi@enovance.com>

diff --git a/build/repositories b/build/repositories
--- a/build/repositories
+++ b/build/repositories
@@ -166,6 +166,17 @@ add_rhn_channel() {
     update_system $dir
 }
 
+add_rh_cdn_repo() {
+    local repo=$1
+
+    check_usage $# 1 "add_rh_cdn_repo <repo>"
+
+    do_chroot $dir subscription-manager repos --enable=$repo
+    if [ "$?" != "0" ]; then
+        echo "Failed to add ${repo} Red Hat CDN repository"
+    fi
+}
+
 add_scn_feature() {
     local dist=$1
     local scn=$2
