build/repositories: list available pools if fail to attach
When failing to attach to a pool, it's useful to have the list of the
available pools that we can attach to.

diff --git a/build/repositories b/build/repositories
--- a/build/repositories
+++ b/build/repositories
@@ -181,6 +181,11 @@ attach_pool_rh_cdn() {
     check_usage $# 2 "attach_pool_rh_cdn <dir> <pool-id>"
 
     do_chroot $target subscription-manager attach --pool $pool
+    if [ "$?" != "0" ]; then
+        echo "Failed at attaching to the pool."
+        echo "You have to select a valid pool from this list:"
+        do_chroot $target subscription-manager list --available
+    fi
 }
 
 add_rh_cdn_repo() {
