Red Hat: add unregister_cdn function
unregister_cdn is the new function used by Red Hat 7 builds to
unregister to CDN account.

Signed-off-by: Emilien Macchi <emilien.macchi@enovance.com>

diff --git a/build/repositories b/build/repositories
--- a/build/repositories
+++ b/build/repositories
@@ -117,6 +117,13 @@ remove_epel_repository() {
     esac
 }
 
+unregister_cdn() {
+    do_chroot $dir subscription-manager unregister
+    if [ "$?" != "0" ]; then
+        echo "Failed to unregister to Red Hat CDN subscription"
+    fi
+}
+
 unregister_rhn() {
     local dist=$1
     local target=$2
